### ISSUE TITLE
Prison Break

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-anticheat#59]
### Possible prison breaks

- [x] Summoned by a GM (.sum)
- [x] Summoned a warlock's box
- [x] Summoned a masmorra encounter stone
- [x] BG Queues
- [x] ARENA
- [x]  DUNGEON

**Comment by Tony931023** [comment]
@acidmanifesto 
All tested, and all allow you to break out of prison.

You have to see if there is any flag that can be applied to the player so that he is not invited to the group, nor does he allow you to sign up in queues, or try to make a map change check that compares with some record in bd that you are in prison and you return back to prison

**Comment by acidmanifesto** [comment]
do u know if it breaks the shackle spell?

**Comment by Tony931023** [comment]
yes

**Comment by acidmanifesto** [comment]
> 

I will say for a fact. GM Summons. we can not do anything about that one at all. GM is the person that has the premissions to make the decision and choices dealing with bans and kicks of the server but also for assisting the server thru tickets and such. So GM Summons will have to be ignored in this case. However. The rest i see as a valid concern.

- [ ] Summoned by a GM (.sum)  <-- Intention due to the role played by the GM
- [x] Summoned a warlock's box  <-- will evaulatue but is a concern
- [x] Summoned a masmorra encounter stone <-- will evaulatue but is a concern
- [x] BG Queues <-- will evaulatue but is a concern
- [x] ARENA <-- will evaulatue but is a concern
- [x]  DUNGEON <-- will evaulatue but is a concern

**Comment by Tony931023** [comment]
meanwhile something similar to keepout could be implemented, for example if you have enabled in the configuration send the player to the prison and check if it is also check the prison break (This would be new), when playing change the ID of the map and the Zone ID would be returned to the jail, this would temporarily prevent all possible jailbreaks mentioned above in this issues #59, it could also prevent a little less crash in this issues #55

I tried to do something but I did not find the correct way to implement it.


[https://github.com/Tony931023/mod-anticheat/blob/mapcheck/src/jailbreak.cpp](https://github.com/Tony931023/mod-anticheat/blob/mapcheck/src/jailbreak.cpp)

@acidmanifesto

**Comment by acidmanifesto** [comment]
I'm going to make this as enhancement\bug\help wanted. As much as i Want to address all issues with auto jailing, the real major issue is the lack of sniffs we have on the jail, since the GM Jail\GM ISLAND was removed in bfa, and and all possiblities of obtaining sniffs is gone, its been confirmed thru data mining that gm jail\gm island is not currently in classics currently as well. And to be honst, i never seen a sniff for gm island or gm jail, so at this point we will just have to wing it with whatever pr or ideas that may come in.

**Comment by acidmanifesto** [comment]
Partially addressed.
https://github.com/azerothcore/mod-anticheat/commit/b78ce2399cdc338468ebe488374a41d661aa1f55

**Comment by acidmanifesto** [comment]
@Tony931023 what is the spell\item ids for the  warlock's box and masmorra encounter stone. I am having issues attempting to identify those on my end.

**Comment by Tony931023** [comment]
let me see if i can find them

**Comment by Tony931023** [comment]
thinking now, if there is a mage also in prison and he invokes a portal he could also escape, we have to try this too

**Comment by Tony931023** [comment]
Ritual of Summoning:
 SPELL [698](https://wotlkdb.com/?spell=698)
object: https://wotlkdb.com/?object=194108

Could player one be implemented to stay in combat while in prison? so it could not be winged by the sorcerer or the summoning stone? @acidmanifesto

**Comment by Tony931023** [comment]
I'm going to compile and test the changes, and by the way I'm also going to test if you can go through a mage portal

**Comment by acidmanifesto** [comment]
> I'm going to compile and test the changes, and by the way I'm also going to test if you can go through a mage portal

That is fine, if the spell casting is resolved with the jail break, would you be ok in having this issue closed since all will be left is the gm summon issue you have posted already as a seperate issue?

**Comment by Tony931023** [comment]
I do believe that the PR could be closed.
