### ISSUE TITLE
Teleport hack false positive when riding with a friend (mount)

### ISSUE THREAD

**Issue by wow-private-servers** [azerothcore/mod-anticheat#68]
### Current Behaviour

Teleport hack false positive when riding with a friend (mount)
https://www.wowhead.com/item=44413/mekgineers-chopper as example

![image](https://user-images.githubusercontent.com/97901840/163995143-c90fd371-b272-4233-880a-cf1182f053d5.png)

### Expected Blizzlike Behaviour

Shouldn't trigger the teleport hack detection

### Steps to reproduce the problem

Mount with item 44413, invite player to party and let him enter the bike.
After riding, exit the mount and you'll get a false positive.

### AC rev. hash/commit

Lastest.

### Operating system

Linux, Win x64

**Comment by acidmanifesto** [comment]
same thing as issue #67 apparrently.
please update your azerothcore and also ensure the anticheat module is updated as well.
the issue although a bit different from the flight manager fix, was essentially the same issue in debugger mode as i followed thru it. Issue was fixed two weeks ago. The issue was additional helpers needed in azerothcore. Please update azerothcore to the latest revision or to rev https://github.com/azerothcore/azerothcore-wotlk/commit/446546fb9668761e3ca28c0ff5b93034122cac99 at a minimal

**Comment by wow-private-servers** [comment]
This one is still giving false positives

**Comment by wow-private-servers** [comment]
did you exit the mount? Just running with the mount doesnt trigger it, only once you exit the mount

**Comment by acidmanifesto** [comment]
> did you exit the mount? Just running with the mount doesnt trigger it, only once you exit the mount

I did. Try updating azerothcore again. There may of been a helper hook that somehow went missing that i literally just readded just a few mins ago
