### ISSUE TITLE
Jump hack error report 

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-anticheat#92]
### Current Behaviour

When the player has the priest's spell floating, and then run top on the water, multiple consecutive reports, and then a team of people all jailed.
![1661848948865](https://user-images.githubusercontent.com/33601959/187393402-e3f571f1-1390-4648-91b6-52a932b917a7.png)

### Expected Blizzlike Behaviour

this is normal work and not hack condition.

### Steps to reproduce the problem

In the instance steam cellar, with the priest's spell floating run on the water. error report happen.

### AC rev. hash/commit

the last version.

### Operating system

debian 11 x64

**Comment by acidmanifesto** [comment]
> 

spell id?

**Comment by kissingers** [comment]
with 1706   on water

**Comment by acidmanifesto** [comment]
> with 1706 on water

i cast 1706 and walk on the water. I cast 1706 while in water.
I get no false hit. Did you update the anticheat to latest?

**Comment by kissingers** [comment]
the problem appear on outland  instance SteamVault
and not the last version ,but almost last 
![image](https://user-images.githubusercontent.com/33601959/187433659-018a419a-8a7b-400b-a7a0-28b8b1c46574.png)

**Comment by acidmanifesto** [comment]
Ensure you have the latest version first. There was alot of substantial changes to detect new jump hack fly alternatives.
If the problem still exsist then i need:
.gps of the location 
or provide the anticheat.log since i incorporated a .go xyz in the logs now.

Video would be helpful but not required at the moment.

**Comment by kissingers** [comment]
Ok, I will update and test after finished the teams raid.

**Comment by Awixs777** [comment]
@acidmanifesto 
I will add here, since it is also connected with the jump hack. I understand that these are custom objects, but this is a maze of pipes. When a player simply runs through the pipes and does nothing else, anti-cheat is triggered. Is it possible to fix it somehow? I really don't want to disable jump hack detection.
Video https://drive.google.com/file/d/1xEZ5RKFlGC3CT0efo3TEswqJRLzep06E/view?usp=sharing

**Comment by acidmanifesto** [comment]
> @acidmanifesto 
> I will add here, since it is also connected with the jump hack. I understand that these are custom objects, but this is a maze of pipes. When a player simply runs through the pipes and does nothing else, anti-cheat is triggered. Is it possible to fix it somehow? I really don't want to disable jump hack detection.
> Video https://drive.google.com/file/d/1xEZ5RKFlGC3CT0efo3TEswqJRLzep06E/view?usp=sharing

Do u have a .gps or a log with a .gps for me to investigate

**Comment by Awixs777** [comment]
@acidmanifesto  .go xyz -7310.128418 -4825.509766 97.445381 1
ID GOB: 184117 
![Screenshot_15](https://user-images.githubusercontent.com/47874183/187529157-262512ce-2cc5-4b20-8b4f-3992439f47ab.png)

**Comment by acidmanifesto** [comment]
> .go xyz -7310.128418 -4825.509766 97.445381 1

thank you. i will check it out now

**Comment by acidmanifesto** [comment]
> 

You issue is that this is a custom spot with gameobjects and not a wmo\m2 with vmaps and mmaps generation. so it registers the player hieght very high above the ground and not flying. Air Transports wont flag it because airt ransports are transports and are their own maps. Although i can not really offer any real support dealing with this case as there is not a spot like this at all in current wotlk that will match this exact enviroment I can however off you a example to exempt the check from operating above a certain Z float elevation and area.


In you case if u want to exempt it from a certain elevation from detecting it.

A example in your case will be to add
```
        if ((player && movementInfo.pos.GetPositionZ() > ANY_ELEVATION_ABOVE_THIS_AS_A_FLOAT_0.0F_EXAMPLE) && player->GetAreaId() == AREA_ID)
        {
            return;
        }
 ```
 
Between here of the void AnticheatMgr::JumpHackDetection(Player* player, MovementInfo movementInfo, uint32 opcode):
![image](https://user-images.githubusercontent.com/16887899/187533724-1cd4a842-74d5-4ff0-aeaa-be68ffdfea02.png)

**Comment by Awixs777** [comment]
@acidmanifesto 
Thanks for the detailed answer and for the solution, albeit a cardinal one. But there is a strange moment, if you place these objects a little higher, there will be no anti-cheat triggers... Video: https://drive.google.com/file/d/1qZK2zwPwcXXf5rlggh0H855t48RTQ-hF/view?usp=sharing

**Comment by acidmanifesto** [comment]
> @acidmanifesto 
> Thanks for the detailed answer and for the solution, albeit a cardinal one. But there is a strange moment, if you place these objects a little higher, there will be no anti-cheat triggers... Video: https://drive.google.com/file/d/1qZK2zwPwcXXf5rlggh0H855t48RTQ-hF/view?usp=sharing

Without knowing the exactly elevation, chance are you are exceeding the max collision height of the area. I am not entirely sure what the issues may result to the server if any in doing so but do proceed at your own discretion.

**Comment by kissingers** [comment]
update to laster version. 
This is gps info
![image](https://user-images.githubusercontent.com/33601959/187567209-d3e62838-76c6-4184-a252-096e2d4d64a3.png)

This is vedio
[2022-08-31 08-17-56.zip](https://github.com/azerothcore/mod-anticheat/files/9457357/2022-08-31.08-17-56.zip)

**Comment by acidmanifesto** [comment]
> update to laster version. This is gps info ![image](https://user-images.githubusercontent.com/33601959/187567209-d3e62838-76c6-4184-a252-096e2d4d64a3.png)
> 
> This is vedio [2022-08-31 08-17-56.zip](https://github.com/azerothcore/mod-anticheat/files/9457357/2022-08-31.08-17-56.zip)

please try https://github.com/azerothcore/mod-anticheat/commit/d6a690125c8118898f0407a80729aedec9bc219e

**Comment by kissingers** [comment]
It seems fixed the problem, including the shaman's water walking, druid swimming are all ok.

**Comment by acidmanifesto** [comment]
> It seems fixed the problem, including the shaman's water walking, druid swimming are all ok.

Thank you for your report.
